/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Bank { 
    accountId: string;
    name: string;
    phone?: string;
    type: Bank.AccountTypeEnum;
    branchCode: string;
}

export namespace Bank {
    export type AccountTypeEnum = 'CHEQUE' | 'SAVINGS'| 'EWALLET' | 'TRANSMISSION';
    export const AccountTypeEnum = {
        CURRENT: 'CHEQUE' as AccountTypeEnum,
        SAVINGS: 'SAVINGS' as AccountTypeEnum,
        EWALLET: 'EWALLET' as AccountTypeEnum,
        TRANSMISSION: 'TRANSMISSION' as AccountTypeEnum
    }; 
}
