/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Bank } from './bank';
import { BusinessHours } from './businessHours';
import { ProfileAvailabilityStatus } from './models';
import { Stock } from './stock';

/**
 * Delivery category (Issue #10).
 * image is a public S3 URL — empty string means no image uploaded yet.
 * id is assigned by the backend; use a temporary UUID client-side for newly added categories
 * until the store is saved and the backend echoes the persisted id.
 */
export interface Category {
  id: string;
  name: string;
  image: string;
  active: boolean;
}

export interface StoreProfile {
    brandSecondaryColor?: string;
    brandPrimaryColor?: string;
    shortName?: string; 
    address?: string;
    badges?: number;
    bank?: Bank;
    businessHours?: Array<BusinessHours>;
    date?: Date;
    description?: string;
    featured?: boolean;
    featuredExpiry?: Date;
    hasVat?: boolean;
    id?: string;
    imageUrl?: string;
    latitude?: number;
    likes?: number;
    longitude?: number;
    mobileNumber?: string;
    emailAddress?: String;
    modifiedDate?: Date;
    name?: string;
    ownerId?: string;
    regNumber?: string;
    responseTimeMinutes?: number;
    role?: StoreProfile.RoleEnum;
    servicesCompleted?: number;
    stockList?: Array<Stock>;
    storeType?: StoreProfile.StoreTypeEnum;
    tags?: Array<string>;
    verificationCode?: string;
    yearsInService?: number;
    storeOffline?: boolean;
    deliversFromMultipleAddresses?: boolean;
    storeMessenger?: Array<StoreMessenger>;
    availabilityStatus?: ProfileAvailabilityStatus.Availability;
    generateMissingImages?: boolean;
    rates: StoreRates;
    profileApproved?: boolean;
    profileApprovedDate?: Date;
    /**
     * RP-005b: referral code of the Referral Partner who assisted in registering this store.
     * Populated from the ?ref= query param captured at the start of the /business registration
     * flow and sent to the backend on store creation (POST /store).
     * Field name confirmed with RP-005a backend ticket — update if backend contract differs.
     */
    referralCode?: string;
    /**
     * Delivery categories configured for this store (Issue #10).
     * Optional to avoid breaking existing code — treat undefined/null as [].
     */
    categories?: Category[];
}

export interface StoreMessenger {
    name?: string
}

export namespace StoreProfile {
    export type RoleEnum = 'CUSTOMER' | 'STORE_ADMIN' | 'STORE' | 'MESSENGER' | 'MESSENGER_ADMIN' | 'ADMIN' | 'AMBASSADOR' | 'REFERRAL_PARTNER';
    export const RoleEnum = {
        CUSTOMER: 'CUSTOMER' as RoleEnum,
        STOREADMIN: 'STORE_ADMIN' as RoleEnum,
        STORE: 'STORE' as RoleEnum,
        MESSENGER: 'MESSENGER' as RoleEnum,
        MESSENGERADMIN: 'MESSENGER_ADMIN' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum,
        AMBASSADOR: 'AMBASSADOR' as RoleEnum,
        REFERRALPARTNER: 'REFERRAL_PARTNER' as RoleEnum
    };
    export type StoreTypeEnum = 'FOOD' | 'CLOTHING' | 'SALON' | 'CAR_WASH';
    export const StoreTypeEnum = {
        FOOD: 'FOOD' as StoreTypeEnum,
        CLOTHING: 'CLOTHING' as StoreTypeEnum,
        SALON: 'SALON' as StoreTypeEnum,
        CARWASH: 'CAR_WASH' as StoreTypeEnum
    };
}

export interface StoreRates {
    standardDeliveryPrice?: number;
    standardDeliveryPriceBike?: number;
    standardDeliveryPriceCar?: number;
    standardDeliveryPriceBakkie?: number;
    standardDeliveryPriceTruck?: number;
    standardDeliveryKm?: number;
    ratePerKmBike?: number;
    ratePerKmCar?: number;
    ratePerKmBakkie?: number;
    ratePerKmTruck?: number;
    ratePerKm?: number;
    ratePerVolumeCM2?: number;
    ratePerWeightKg?: number;
    labourRatePerFloor?: number;
}
