/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Bank } from './bank';
import { BusinessHours } from './businessHours';
import { Stock } from './stock';
import { StoreRates } from './storeProfile';


export interface StoreSummary {
    description?: string;
    id?: string;
    imageUrl?: string;
    latitude?: number;
    longitude?: number;
    group?: string;
    name?: string
    rates: StoreRates;
}

export interface StoreMessenger {
    name?: string
}

export namespace StoreProfile {
    export type RoleEnum = 'CUSTOMER' | 'STORE_ADMIN' | 'STORE' | 'MESSENGER';
    export const RoleEnum = {
        CUSTOMER: 'CUSTOMER' as RoleEnum,
        STOREADMIN: 'STORE_ADMIN' as RoleEnum,
        STORE: 'STORE' as RoleEnum,
        MESSENGER: 'MESSENGER' as RoleEnum
    };
    export type StoreTypeEnum = 'FOOD' | 'CLOTHING' | 'SALON' | 'CAR_WASH';
    export const StoreTypeEnum = {
        FOOD: 'FOOD' as StoreTypeEnum,
        CLOTHING: 'CLOTHING' as StoreTypeEnum,
        SALON: 'SALON' as StoreTypeEnum,
        CARWASH: 'CAR_WASH' as StoreTypeEnum
    };
}
