/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Bank } from './bank';


export interface UserProfile { 
    address?: string;
    badges?: number;
    bank: Bank;
    date?: Date;
    description?: string;
    id?: string;
    idNumber?: string;
    dateOfBirth?: string;
    imageUrl: string;
    latitude?: number;
    likes?: number;
    longitude?: number;
    mobileNumber?: string;
    emailAddress?: string;
    modifiedDate?: Date;
    name?: string;
    surname?: string;
    email?: string
    responseTimeMinutes?: number;
    role?: UserProfile.RoleEnum;
    servicesCompleted?: number;
    verificationCode?: string;
    yearsInService?: number;
    termsAccepted?: boolean;
    termsAcceptedDate?: Date;
    icaAccepted?: boolean;
    icaAcceptedDate?: Date;
    icaVersion?: string;
    availabilityStatus?: ProfileAvailabilityStatus.Availability;
    profileApproved?: boolean;
    profileApprovedDate?: Date;
    missingDocumentsReminderSent?: boolean;
    welcomeMessageSent?: boolean;
    crminalCheckData?: CriminalCheckData;
    tag : { [key: string]: any };
    ambassadorId?: string | null;
}
export namespace UserProfile {
    export type RoleEnum = 'CUSTOMER' | 'STORE_ADMIN' | 'STORE' | 'MESSENGER' | 'MESSENGER_ADMIN' | 'ADMIN' | 'AMBASSADOR';
    export const RoleEnum = {
        CUSTOMER: 'CUSTOMER' as RoleEnum,
        STOREADMIN: 'STORE_ADMIN' as RoleEnum,
        STORE: 'STORE' as RoleEnum,
        MESSENGER: 'MESSENGER' as RoleEnum,
        MESSENGERADMIN: 'MESSENGER_ADMIN' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum,
        AMBASSADOR: 'AMBASSADOR' as RoleEnum
    };
}

export namespace ProfileAvailabilityStatus {
        export type Availability = 'ONLINE' | 'OFFLINE' | 'AWAY';
        export const Availability = {
            ONLINE: 'ONLINE' as Availability,
            OFFLINE: 'OFFLINE' as Availability,
            AWAY: 'AWAY' as Availability
        };
    }   

export interface CriminalCheckData {
    criminalRecordCheckAccepted?: boolean;
    criminalCheckMessageSent?: boolean;
    criminalRecordCheckDate?: Date;
    criminalRecordCheckDocument?: DocumentAttachment;
    criminalCheckPass?: boolean;
}

export interface DocumentAttachment {
    name: string
    url: string
    uploadedDate: Date
}
